# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# TEST DATA

Tag.create(name: "Food")
Tag.create(name: "Nightlife")
Tag.create(name: "Restaurant")
Tag.create(name: "Shopping")
# Tag.create(name: "Arts & Entertainment")

User.create(username: "Steph C.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_38/v1473445178/user1_saypqj.jpg")
User.create(username: "Michael J.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,w_38/v1473445178/user2_etxbyg.jpg")
User.create(username: "Jessica K.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_38/v1473445178/user3_cwsrwd.jpg")
User.create(username: "Nick P.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,w_38/v1473445178/user4_r9ilhs.jpg")
User.create(username: "Lana V.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,w_38/v1473445178/user5_jyqjao.jpg")
User.create(username: "Dan M.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,w_38/v1473445178/user6_rjtokl.jpg")
User.create(username: "Charity L.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,w_38/v1473445177/user7_eukr1y.jpg")
User.create(username: "Rick S.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_38/v1473445177/user8_sgqaqv.jpg")
User.create(username: "Morty S.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_38/v1473445177/user9_xvhfzn.jpg")
User.create(username: "Alex S.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_38/v1473445177/user10_kbsydp.jpg")
User.create(username: "Karen D.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,w_38/v1473445177/user11_qqgsql.jpg")
User.create(username: "Carol K.", password: "123456", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_38/v1473445177/user12_hd2drw.jpg")

#Food Businesses
Business.create(name: "Halal Cart", lat: 37.790837, lng: -122.398464, street_address: "455 Market St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473391795/halalcart_s7oyrv.jpg")
Tagging.create(business_id: 1, tag_id: 1)
Tagging.create(business_id: 1, tag_id: 3)
Review.create(business_id: 1, user_id: 4, rating: 4, content: "Best $10 you'll ever spend.")
Review.create(business_id: 1, user_id: 5, rating: 4, content: "BEWARE!! It's cash only!")
Review.create(business_id: 1, user_id: 12, rating: 4, content: "Food is sooooo amazing!")
Review.create(business_id: 1, user_id: 10, rating: 4, content: "Don't forget to get a drink! Goes so well with everything here!")
Review.create(business_id: 1, user_id: 9, rating: 4, content: "Ask for the secret sauce!")
Image.create(business_id: 1, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473391798/halalcart1_cmqkwg.jpg")
Image.create(business_id: 1, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473391797/halalcart2_kmk1vq.jpg")
Image.create(business_id: 1, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473391798/halalcart3_psgzlt.jpg")

Business.create(name: "Tacos Negris", lat: 37.576156, lng: -121.976658, street_address: "37721 Niles Blvd", city_state_address: "Fremont, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473392666/tacosnegris_d7moke.jpg")
Tagging.create(business_id: 2, tag_id: 1)
Review.create(business_id: 2, user_id: 3, rating: 5, content: "Add avocados to whatever you get. You won't regret it.")
Review.create(business_id: 2, user_id: 2, rating: 5, content: "THE SHRIMP BURRITO CHANGED MY LIFE")
Review.create(business_id: 2, user_id: 7, rating: 4, content: "Don't forget to get a drink! Goes so well with everything here!")
Review.create(business_id: 2, user_id: 5, rating: 4, content: "I got one of every taco. Then I went back and did it again. For the same meal.")
Image.create(business_id: 2, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473392754/tacosnegris4_qzwaic.jpg")
Image.create(business_id: 2, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473392667/tacosnegris3_shklap.jpg")
Image.create(business_id: 2, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473392667/tacosnegris1_lhlpnu.jpg")

Business.create(name: "Crepes A Go Go", lat: 37.769735, lng: -122.412156, street_address: "428 11th St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473392990/crepes_bkdksu.jpg")
Tagging.create(business_id: 3, tag_id: 1)
Review.create(business_id: 3, user_id: 7, rating: 5, content: "SO SOFT")
Review.create(business_id: 3, user_id: 9, rating: 4, content: "I didn't know heaven tasted like this.")
Review.create(business_id: 3, user_id: 3, rating: 5, content: "If you're drunk at night but you don't want to devour a heavy meal, this will do the job.")
Image.create(business_id: 3, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473392992/crepes1_wh79zm.jpg")
Image.create(business_id: 3, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473392992/crepes2_mos7md.jpg")
Image.create(business_id: 3, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473392992/crepes3_unk0fu.jpg")

Business.create(name: "Tacos Santiaguito", lat: 37.315708, lng: -121.976639, street_address: "609 Saratoga Ave", city_state_address: "San Jose, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473393449/tacosSanti_rxnska.jpg")
Tagging.create(business_id: 4, tag_id: 1)
Review.create(business_id: 4, user_id: 12, rating: 4, content: "Food is sooooo amazing!")
Review.create(business_id: 4, user_id: 8, rating: 4, content: "Limes. LIMES ON EVERYTHING!!!")
Review.create(business_id: 4, user_id: 7, rating: 4, content: "Ask for the secret sauce!")
Review.create(business_id: 4, user_id: 3, rating: 4, content: "I had a great experience the last 2 times I was here. I came here for lunch on a friday and dinner on a saturday. yes, i went two days in a row!")
Review.create(business_id: 4, user_id: 1, rating: 5, content: "Some amazing prices, especially on meats & fish")
Image.create(business_id: 4, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473393451/tacossanti1_rusnsc.jpg")
Image.create(business_id: 4, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473393452/tacossanti2_a9vzb7.jpg")
Image.create(business_id: 4, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473393450/tacossanti3_k7vxz3.jpg")

Business.create(name: "In-N-Out Burger", lat: 37.807706, lng: -122.418728, street_address: "333 Jefferson St", city_state_address: "San Francisco, CA", profile_image_url:"http://res.cloudinary.com/dnmknegr2/image/upload/v1473178655/innout_lasqux.jpg")
Tagging.create(business_id: 5, tag_id: 1)
Tagging.create(business_id: 5, tag_id: 3)
Review.create(business_id: 5, user_id: 1, rating: 5, content: "animal fries are soooooo gooooood")
Review.create(business_id: 5, user_id: 3, rating: 4, content: "wish i could give it 6 stars tbh")
Review.create(business_id: 5, user_id: 10, rating: 4, content: "Don't forget to get a drink! Goes so well with everything here!")
Review.create(business_id: 5, user_id: 2, rating: 5, content: "BANANA PEPPERS ARE A MUST")
Review.create(business_id: 5, user_id: 7, rating: 4, content: "Always get more spread!")
Review.create(business_id: 5, user_id: 4, rating: 5, content: "did you know you can get well done fries?!")
Image.create(business_id: 5, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473267361/innout1_il9d2b.jpg")
Image.create(business_id: 5, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473267361/innout2_i8nhh1.jpg")
Image.create(business_id: 5, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473267361/innout3_ibowb6.jpg")

Business.create(name: "Butterscotch On The Go", lat: 37.454579, lng: -122.163221, street_address: "60 Middlefield Rd", city_state_address: "Palo Alto, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473394034/butterscotch_jyq8vd.jpg")
Tagging.create(business_id: 6, tag_id: 1)
Review.create(business_id: 6, user_id: 5, rating: 5, content: "all it takes is one bite and you're hooked")
Review.create(business_id: 6, user_id: 2, rating: 4, content: "It's not too sweet, has a great consistency and goes really well with the almond brittle and whipped cream.")
Review.create(business_id: 6, user_id: 8, rating: 4, content: "I have never had pudding quite like this and I could eat this almost everyday and I'm not a pudding person.")
Review.create(business_id: 6, user_id: 10, rating: 5, content: "They are a wonderful addition to the Edgewood Eats scene!")
Review.create(business_id: 6, user_id: 10, rating: 4, content: "Don't forget to get a drink! Goes so well with everything here!")
Image.create(business_id: 6, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473394035/butterscotch1_uc4ftz.jpg")
Image.create(business_id: 6, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473394035/butterscotch2_tpcyhz.jpg")
Image.create(business_id: 6, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473394035/butterscotch3_juonx9.jpg")

Business.create(name: "Mamacitas Tacos", lat: 37.400934, lng: -122.106229, street_address: "555 Showers Dr", city_state_address: "Mountain View, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473394556/mamacitas_xzc5kp.jpg")
Tagging.create(business_id: 7, tag_id: 1)
Review.create(business_id: 7, user_id: 10, rating: 4, content: "Ask for the secret sauce!")
Review.create(business_id: 7, user_id: 11, rating: 4, content: "Get the super burrito with al pastor and try the green salsa if you like hot and spicy!")
Review.create(business_id: 7, user_id: 4, rating: 4, content: "Everything is just so fresh. Holy smokes.")
Review.create(business_id: 7, user_id: 3, rating: 5, content: "All of their salsas are soild")
Image.create(business_id: 7, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473394559/mamcitas1_h1pldq.jpg")
Image.create(business_id: 7, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473394557/mamacitas2_kkocvg.jpg")
Image.create(business_id: 7, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473394558/mamacitas3_j6r5ry.jpg")

Business.create(name: "Taqueria Sinaloa", lat: 37.784892, lng: -122.238162 , street_address: "2138 International Blvd", city_state_address: "Oakland, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473394924/taqsin_zyaj2k.jpg")
Tagging.create(business_id: 8, tag_id: 1)
Review.create(business_id: 8, user_id: 2, rating: 5, content: "My #1 Taco truck in the town.")
Review.create(business_id: 8, user_id: 8, rating: 4, content: "Growing up in Southern California, taco trucks/stands are a dime a dozen, but good ones are rare. This is it.")
Review.create(business_id: 8, user_id: 4, rating: 3, content: "Satisfies my craving for tacos every time.")
Review.create(business_id: 8, user_id: 5, rating: 4, content: "Food is sooooo amazing!")
Review.create(business_id: 8, user_id: 1, rating: 5, content: "LIFE CHANGING BURRITO ALERT")
Review.create(business_id: 8, user_id: 10, rating: 5, content: "I've lived in Oakland for years and I can't believe I didn't hear of this place until this week. WHAT AM I DOING WITH MY LIFE???")
Image.create(business_id: 8, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473394925/taqsin1_moiwvf.jpg")
Image.create(business_id: 8, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473394925/taqsin2_wzipub.jpg")
Image.create(business_id: 8, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473394925/taqsin3_muev8k.jpg")

Business.create(name: "Tacos Mi Rancho", lat: 37.798946, lng: -122.256504, street_address: "1434 1st Ave", city_state_address: "Oakland, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473395299/tacosmr_ctuyke.jpg")
Tagging.create(business_id: 9, tag_id: 1)
Review.create(business_id: 9, user_id: 5, rating: 4, content: "They are open late night too so definitely a good place to stop by after a night of drinking in Oakland.")
Review.create(business_id: 9, user_id: 3, rating: 4, content: "The meat is tender and juicy!")
Review.create(business_id: 9, user_id: 8, rating: 4, content: "Food is sooooo amazing!")
Review.create(business_id: 9, user_id: 4, rating: 4, content: "Don't forget to get a drink! Goes so well with everything here!")
Review.create(business_id: 9, user_id: 11, rating: 3, content: "Eat them quick before they get soggy!")
Review.create(business_id: 9, user_id: 12, rating: 5, content: "The pickled carrots they offer on the side are TASTY")
Image.create(business_id: 9, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473395302/tacosmr1_cry3wp.jpg")
Image.create(business_id: 9, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473395302/tacosmr2_d7azlh.jpg")
Image.create(business_id: 9, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473395300/tacosmr3_ecriir.jpg")

Business.create(name: "Shrimp Falafel Mix", lat: 37.811838, lng: -122.283019, street_address: "18th St Ave", city_state_address: "Oakland, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473395623/shrimpfal_yjs7bw.jpg")
Tagging.create(business_id: 10, tag_id: 1)
Review.create(business_id: 4, user_id: 7, rating: 4, content: "Ask for the secret sauce!")
Review.create(business_id: 10, user_id: 10, rating: 4, content: "FRESH FALAFELS FOR LIFE!")
Image.create(business_id: 10, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473395625/shrimpfal1_pll45d.jpg")
Image.create(business_id: 10, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473395625/shrimpfal2_y7w0sa.jpg")
Image.create(business_id: 10, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473395625/shrimpfal3_h7jb84.jpg")

#Nightlife
Business.create(name: "Mr. Smith's", lat: 37.779977, lng: -122.412254, street_address: "34 7th St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473143561/mrsmiths_klc2mw.jpg")
Tagging.create(business_id: 11, tag_id: 2)
Review.create(business_id: 11, user_id: 2, rating: 5, content: "Great vibes")
Review.create(business_id: 11, user_id: 3, rating: 4, content: "The first floor is relatively small like a bar/saloon. You go downstairs, and there's a dance floor. Sign up for the guestlist and don't pay cover.")
Review.create(business_id: 11, user_id: 8, rating: 4, content: "Everyone is so nice here!")
Review.create(business_id: 11, user_id: 1, rating: 4, content: "OMG I had one of the best times ever!")
Review.create(business_id: 11, user_id: 10, rating: 5, content: "Chill place, good drinks, good music (top40/hip-hop), crowded but spacious by the end of the night.")
Image.create(business_id: 11, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473437428/smiths1_jz8dim.jpg")
Image.create(business_id: 11, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473437428/smiths2_igocky.jpg")
Image.create(business_id: 11, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473437428/smiths3_o5wqef.jpg")

Business.create(name: "Temple Nightclub", lat: 37.787891, lng: -122.397171, street_address: "540 Howard St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473143561/temple_oso79h.jpg")
Tagging.create(business_id: 12, tag_id: 2)
Review.create(business_id: 12, user_id: 4, rating: 3, content: "bouncer was kinda mean, didn't trust my id")
Review.create(business_id: 12, user_id: 1, rating: 2, content: "the music is alright here; it's all top 40's!")
Review.create(business_id: 12, user_id: 12, rating: 3, content: "Nice remodel, but pushy staff. Get on the guest list for free admission before 11pm.")
Image.create(business_id: 12, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473437802/temple1_dcgpel.png")
Image.create(business_id: 12, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473437799/temple2_wqg0su.jpg")
Image.create(business_id: 12, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473437799/temple3_hghudx.jpg")

Business.create(name: "Rye", lat: 37.786757, lng: -122.414601, street_address: "688 Geary St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473143561/rye_honktk.jpg")
Tagging.create(business_id: 13, tag_id: 2)
Review.create(business_id: 13, user_id: 10, rating: 5, content: "really nice looking bar here!")
Review.create(business_id: 13, user_id: 2, rating: 4, content: "the drinks are strong, would definitely recommend!")
Image.create(business_id: 13, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473437980/rye1_shph1s.jpg")
Image.create(business_id: 13, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473437979/ry2_brzsmq.jpg")
Image.create(business_id: 13, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473437979/rye3_yquaev.jpg")

Business.create(name: "Noc Noc", lat: 37.771775, lng: -122.431401, street_address: "557 Haight St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473143561/nocnoc_ewabna.jpg")
Tagging.create(business_id: 14, tag_id: 2)
Review.create(business_id: 14, user_id: 9, rating: 5, content: "The drinks aren't watered down, i love it!")
Review.create(business_id: 14, user_id: 4, rating: 4, content: "The bartenders here are awesome")
Review.create(business_id: 14, user_id: 4, rating: 4, content: "This is one of the coolest bars I have seen in the city!")
Image.create(business_id: 14, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473438218/noc1_hhgn2t.jpg")
Image.create(business_id: 14, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473438217/noc2_bu8asa.jpg")
Image.create(business_id: 14, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473438217/noc3_slo5kp.jpg")

Business.create(name: "The View", lat: 37.784998, lng: -122.404331, street_address: "780 Mission St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473143561/theview_n4e70q.jpg")
Tagging.create(business_id: 15, tag_id: 2)
Tagging.create(business_id: 15, tag_id: 1)
Tagging.create(business_id: 15, tag_id: 3)
Review.create(business_id: 15, user_id: 11, rating: 4, content: "they even have darts here!")
Review.create(business_id: 15, user_id: 7, rating: 4, content: "great view at this spot!!!")
Review.create(business_id: 15, user_id: 1, rating: 3, content: "The view is pretty breathtaking in the main space!")
Review.create(business_id: 15, user_id: 2, rating: 5, content: "You'll be able to look at the beautiful city lights while sipping on some drinks with great company.")
Image.create(business_id: 15, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473438385/view1_zhqdpu.jpg")
Image.create(business_id: 15, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473438385/view2_qibxku.jpg")
Image.create(business_id: 15, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473438385/view3_b2myis.jpg")

Business.create(name: "1015 Folsom", lat: 37.778042, lng: -122.405792, street_address: "1015 Folsom St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473395993/folsom_qlguaz.jpg")
Tagging.create(business_id: 16, tag_id: 2)
Review.create(business_id: 16, user_id: 6, rating: 3, content: "Soooooo crowded all the time.")
Review.create(business_id: 16, user_id: 1, rating: 2, content: "Drinks cost more than a nice dinner. C'monnnn.")
Review.create(business_id: 16, user_id: 2, rating: 4, content: "This club has some of the best artists coming through consistently!")
Review.create(business_id: 16, user_id: 10, rating: 4, content: "Great atmosphere!")
Image.create(business_id: 16, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473395996/folsom1_f7kmqr.jpg")
Image.create(business_id: 16, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473395996/folsom2_f1cdvx.jpg")
Image.create(business_id: 16, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473395995/folsom3_xbbe0p.jpg")

Business.create(name: "Pure Lounge", lat: 37.376763, lng: -122.029862, street_address: "146 S Murphy Ave", city_state_address: "Sunnyvale, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473438563/pure_yam0t8.jpg")
Tagging.create(business_id: 17, tag_id: 2)
Review.create(business_id: 17, user_id: 5, rating: 3, content: "The wait lines are huge!")
Review.create(business_id: 17, user_id: 4, rating: 4, content: "Free guestlist before 11pm and you can RSVP at their website every Saturday.")
Review.create(business_id: 17, user_id: 12, rating: 2, content: "I remember there was a time in my life where I'd come to Pure every single weekend. Those were the days!")
Image.create(business_id: 17, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473438564/pure1_myfy6h.jpg")
Image.create(business_id: 17, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473438563/pure2_cbcnkn.jpg")
Image.create(business_id: 17, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473438563/pure3_v6nj90.jpg")

Business.create(name: "Tequila Shots Bar & Grill", lat: 37.431034, lng: -121.906905, street_address: "38 N Main St", city_state_address: "Milpitas, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473439111/teq_by50fq.jpg")
Tagging.create(business_id: 18, tag_id: 1)
Tagging.create(business_id: 18, tag_id: 2)
Review.create(business_id: 18, user_id: 2, rating: 4, content: "Garlic fries are amazing here!")
Review.create(business_id: 18, user_id: 3, rating: 4, content: "Genuinely surprised by the level of deliciousness of their tacos.")
Review.create(business_id: 18, user_id: 11, rating: 4, content: "They play every big game in the bay at this spot.")
Review.create(business_id: 18, user_id: 7, rating: 5, content: "The owner and bartenders are really accomodating!")
Review.create(business_id: 18, user_id: 6, rating: 4, content: "Carnitas/al pastor tacos + tequila shots = winning")
Image.create(business_id: 18, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473439111/teq1_spdudy.jpg")
Image.create(business_id: 18, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473439111/teq2_reqyac.jpg")
Image.create(business_id: 18, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473439111/teq3_ya5lnp.jpg")

Business.create(name: "55 South", lat: 37.335052, lng: -121.890039, street_address: "55 S 1st St", city_state_address: "San Jose, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473439331/south_mibkjy.jpg")
Tagging.create(business_id: 19, tag_id: 1)
Tagging.create(business_id: 19, tag_id: 2)
Review.create(business_id: 19, user_id: 4, rating: 3, content: "Located in DTSJ and within extreme walking distance of a couple of other bars and maybe some food places.")
Review.create(business_id: 19, user_id: 12, rating: 4, content: "Beef carpaccio was really good")
Review.create(business_id: 19, user_id: 10, rating: 5, content: "A very pleasant lounge feel here.")
Image.create(business_id: 19, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473439331/south1_drqq4y.jpg")
Image.create(business_id: 19, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473439331/south2_ycsi7t.jpg")
Image.create(business_id: 19, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473439331/south3_comsq4.jpg")

Business.create(name: "Ruby Skye", lat: 37.787462, lng: -122.409535, street_address: "420 Mason St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473439695/ruby_odbrd6.jpg")
Tagging.create(business_id: 20, tag_id: 2)
Review.create(business_id: 20, user_id: 5, rating: 3, content: "So many great DJ's come by but the staff is kinda mean")
Review.create(business_id: 20, user_id: 2, rating: 2, content: "Bouncers gave me and my friends a really hard time for having out of state IDs")
Review.create(business_id: 20, user_id: 10, rating: 3, content: "Don't forget to drink water! Young kids these days area always forgetting.")
Review.create(business_id: 20, user_id: 8, rating: 4, content: "Every show is always amazing!")
Image.create(business_id: 20, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473439695/ruby1_bt7wef.jpg")
Image.create(business_id: 20, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473439695/ruby2_mwuoop.jpg")
Image.create(business_id: 20, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473439696/ruby3_ns2w7c.jpg")


#Restaurants
Business.create(name: "La Victoria Taqueria", lat: 37.332550, lng: -121.884531, street_address: "140 E San Carlos St", city_state_address: "San Jose, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473440132/vics_f33bgc.jpg")
Tagging.create(business_id: 21, tag_id: 1)
Tagging.create(business_id: 21, tag_id: 3)
Review.create(business_id: 21, user_id: 1, rating: 4, content: "Put orange sauce on everything. EVERY. THING.")
Review.create(business_id: 21, user_id: 5, rating: 5, content: "Lengua here is always so fresh.")
Review.create(business_id: 21, user_id: 11, rating: 5, content: "Staff is super nice here!")
Review.create(business_id: 21, user_id: 11, rating: 4, content: "Nacho cheese fries are soooo good here")
Review.create(business_id: 21, user_id: 8, rating: 3, content: "Gets really crowded after midnight every night.")
Image.create(business_id: 21, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440133/vics1_af5c9l.jpg")
Image.create(business_id: 21, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440133/vics2_b5si9y.jpg")
Image.create(business_id: 21, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440133/vics3_koaqqc.jpg")

Business.create(name: "Pho Y #1", lat: 37.349840, lng: -121.826901, street_address: "1660 E Capitol Expy", city_state_address: "San Jose, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473440318/phoy_gylgbf.jpg")
Tagging.create(business_id: 22, tag_id: 1)
Tagging.create(business_id: 22, tag_id: 3)
Review.create(business_id: 22, user_id: 5, rating: 5, content: "noodles are so delicious here")
Review.create(business_id: 22, user_id: 3, rating: 5, content: "the broth is amazing!")
Review.create(business_id: 22, user_id: 10, rating: 4, content: "The soup is low in fat, high in taste.")
Review.create(business_id: 22, user_id: 9, rating: 5, content: "Order in Vietnamese and they'll hook it up!")
Review.create(business_id: 22, user_id: 6, rating: 4, content: "Avocado shakes here are ridiculously good")
Image.create(business_id: 22, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440319/phoy1_iinmjl.jpg")
Image.create(business_id: 22, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440319/phoy2_lk4t6c.jpg")
Image.create(business_id: 22, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440319/phoy3_c5seig.jpg")

Business.create(name: "Oren’s Hummus Shop", lat: 37.445615, lng: -122.162280, street_address: "261 University Ave", city_state_address: "Palo Alto, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473440728/oren_onu6ot.jpg")
Tagging.create(business_id: 23, tag_id: 1)
Tagging.create(business_id: 23, tag_id: 3)
Review.create(business_id: 23, user_id: 11, rating: 4, content: "Pita is baked fresh every day!")
Review.create(business_id: 23, user_id: 2, rating: 5, content: "Meat is super savory....")
Review.create(business_id: 23, user_id: 12, rating: 3, content: "The hummus is made from scratch, with LOVE!!!")
Review.create(business_id: 23, user_id: 4, rating: 5, content: "Lines can get long, get here early!")
Review.create(business_id: 23, user_id: 1, rating: 4, content: "The sauces are amazing here.")
Image.create(business_id: 23, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440729/oren1_o0otxm.jpg")
Image.create(business_id: 23, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440729/oren2_ufxbvx.jpg")
Image.create(business_id: 23, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440729/oren3_chvvci.jpg")

Business.create(name: "Homeroom", lat: 37.828623, lng: -122.260080, street_address: "400 40th St", city_state_address: "Oakland, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473440909/homeroom_luzjna.jpg")
Tagging.create(business_id: 24, tag_id: 1)
Tagging.create(business_id: 24, tag_id: 3)
Review.create(business_id: 24, user_id: 5, rating: 4, content: "Heaven for all mac and cheese lovers.")
Review.create(business_id: 24, user_id: 2, rating: 4, content: "Cheesecake here makes for the perfect pairing with mac and cheese")
Review.create(business_id: 24, user_id: 10, rating: 5, content: "So many distinct flavors for every mac and cheese plate... you've got to try them all!!!")
Review.create(business_id: 24, user_id: 9, rating: 5, content: "Is it bad that I come here more than once a week?")
Image.create(business_id: 24, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440910/homeroom2_ojgewa.jpg")
Image.create(business_id: 24, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440910/homeroom1_gnyzqn.jpg")
Image.create(business_id: 24, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473440910/homeroom3_hfvb2e.jpg")

Business.create(name: "Pho 2000", lat: 37.783879, lng: -122.418023, street_address: "637 Larkin St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473441240/pho2000_oopvk3.jpg")
Tagging.create(business_id: 25, tag_id: 1)
Tagging.create(business_id: 25, tag_id: 3)
Review.create(business_id: 25, user_id: 5, rating: 4, content: "Classic Little Saigon Hole-in-the-wall restaurant that offers multiple pages of authentic and comforting Vietnamese food.")
Review.create(business_id: 25, user_id: 4, rating: 3, content: "My friend had the bun rieu, she's the bun rieu queen and she said pho 2000's bun rieu is alright.")
Review.create(business_id: 25, user_id: 7, rating: 5, content: "CASH ONLY!!! Totally worth it.")
Review.create(business_id: 25, user_id: 12, rating: 5, content: "Holy. Smokes. Feels like I'm back in Vietnam.")
Image.create(business_id: 25, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473441240/pho2001_ryyken.jpg")
Image.create(business_id: 25, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473441240/pho2002_ykqxlv.jpg")
Image.create(business_id: 25, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473441240/pho2003_c7yfz9.jpg")

Business.create(name: "Banh Mi Ba Le", lat: 37.786148, lng: -122.241126, street_address: "1909 International Blvd", city_state_address: "Oakland, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473441760/banhmi_lgx7bt.jpg")
Tagging.create(business_id: 26, tag_id: 1)
Tagging.create(business_id: 26, tag_id: 3)
Review.create(business_id: 26, user_id: 3, rating: 5, content: "Each spring roll is handrolled with love.")
Review.create(business_id: 26, user_id: 1, rating: 4, content: "combination banh mi is sooooo bomb.")
Review.create(business_id: 26, user_id: 5, rating: 5, content: "veggies here are so fresh and seasoned so well")
Review.create(business_id: 26, user_id: 11, rating: 5, content: "I can't stop myself from getting 2 orders of banh mi every time I come here!!!")
Image.create(business_id: 26, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473441762/banhmi1_mbax4j.jpg")
Image.create(business_id: 26, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473441761/banhmi2_r6mzwk.jpg")
Image.create(business_id: 26, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473441762/banhmi3_sjowcd.jpg")

Business.create(name: "Cuisine of Nepal", lat: 37.740905, lng: -122.423247, street_address: "3486 Mission St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473442056/nepal1_famlqv.jpg")
Tagging.create(business_id: 27, tag_id: 1)
Tagging.create(business_id: 27, tag_id: 3)
Review.create(business_id: 27, user_id: 3, rating: 5, content: "We tried the palak paneer & prawn curry and highly recommend both.")
Review.create(business_id: 27, user_id: 2, rating: 5, content: "I strongly advise getting the combo since the sides are the actual traditional meals in Nepal.")
Review.create(business_id: 27, user_id: 10, rating: 5, content: "Eat. Here. ASAP.")
Review.create(business_id: 27, user_id: 9, rating: 5, content: "Spectacular food and service!")
Review.create(business_id: 27, user_id: 11, rating: 4, content: "The flavors were really nice and strong.")
Review.create(business_id: 27, user_id: 6, rating: 5, content: "Very authentic food from Nepal!")
Image.create(business_id: 27, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473442056/nepal2_k2rlaj.jpg")
Image.create(business_id: 27, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473442056/nepal3_w8mak0.jpg")
Image.create(business_id: 27, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473442056/nepal4_vabl2z.jpg")

# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )


#Shopping businesses
Business.create(name: "Westfield San Francisco", lat: 37.783889, lng: -122.406424, street_address: "865 Market St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473442472/westfieldsf_zjwo0o.jpg")
Tagging.create(business_id: 28, tag_id: 4)
Review.create(business_id: 28, user_id: 10, rating: 3, content: "The few stores I'll stop by when here are J Crew, Nordstrom, Adidas, and Bloomingdales.")
Review.create(business_id: 28, user_id: 4, rating: 5, content: "It's 7 stories high with spiral escalators!!!")
Review.create(business_id: 28, user_id: 5, rating: 3, content: "It's like a copy of the Caesar's Forum Shops in Las Vegas")
Review.create(business_id: 28, user_id: 11, rating: 4, content: "So much nicer than the other Westfield malls!")
Review.create(business_id: 28, user_id: 6, rating: 4, content: "There's even a Bristol Farms for some artisanal grocery shopping!")
Image.create(business_id: 28, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473442474/wfsf1_p8x9d6.png")
Image.create(business_id: 28, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473442473/wfsf2_ter9hc.jpg")
Image.create(business_id: 28, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473442473/wfsf3_uo5prs.jpg")

Business.create(name: "Westfield Oakridge", lat: 37.251176, lng: -121.862503, street_address: "925 Blossom Hill Rd", city_state_address: "San Jose, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473442785/wfoak_k23vzk.jpg")
Tagging.create(business_id: 29, tag_id: 4)
Review.create(business_id: 29, user_id: 12, rating: 4, content: "They have all of my favorite stores!")
Review.create(business_id: 29, user_id: 4, rating: 4, content: "Movie theatre is on the second floor of the food court.")
Review.create(business_id: 29, user_id: 8, rating: 3, content: "pretty decent mall considering it's the only one in the far south")
Review.create(business_id: 29, user_id: 3, rating: 3, content: "Great place to stroll through on the weekends.")
Image.create(business_id: 29, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473442787/wfoak1_dqqkoc.jpg")
Image.create(business_id: 29, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473442786/wfoak2_z6zymw.jpg")
Image.create(business_id: 29, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473442786/wfoak3_skzvr8.jpg")

Business.create(name: "Eastridge", lat: 37.325381, lng: -121.813295, street_address: "2200 Eastridge Loop", city_state_address: "San Jose, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473443146/eastridge_j3wniu.jpg")
Tagging.create(business_id: 30, tag_id: 4)
Review.create(business_id: 30, user_id: 5, rating: 3, content: "Pretty plain mall if you ask me")
Review.create(business_id: 30, user_id: 3, rating: 3, content: "I only come here to take Christmas photos haha")
Review.create(business_id: 30, user_id: 11, rating: 4, content: "They always go all out for Christmas!")
Review.create(business_id: 30, user_id: 6, rating: 3, content: "Decent shops, not much else though.")
Image.create(business_id: 30, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473443147/eastridge1_omyyhf.jpg")
Image.create(business_id: 30, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473443147/eastridge2_gnlck9.jpg")
Image.create(business_id: 30, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473443147/eastridge3_zxbabe.jpg")

Business.create(name: "Stanford Center", lat: 37.443484, lng: -122.172315, street_address: "660 Stanford Shopping Ctr", city_state_address: "Palo Alto, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473443623/stanford_adwfli.jpg")
Tagging.create(business_id: 31, tag_id: 4)
Review.create(business_id: 31, user_id: 4, rating: 4, content: "All of the primary stores here definitely deliver.")
Review.create(business_id: 31, user_id: 5, rating: 4, content: "Such a pleasant vibe for a mall")
Review.create(business_id: 31, user_id: 10, rating: 5, content: "One of the most beautiful shopping centers I've ever seen in person.")
Review.create(business_id: 31, user_id: 12, rating: 4, content: "Can be pretty expensive here since it's more on the high-end side")
Review.create(business_id: 31, user_id: 1, rating: 5, content: "Looks amazing after the remodel!")
Image.create(business_id: 31, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473443625/stanford1_ngix0f.jpg")
Image.create(business_id: 31, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473443625/stanford2_rzdz5n.jpg")
Image.create(business_id: 31, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473443625/stanford3_lwlwfv.jpg")

Business.create(name: "Valley Fair", lat: 37.325037, lng: -121.945745, street_address: "2855 Stevens Creek Blvd", city_state_address: "Santa Clara, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473444003/wfvf_ohr1wr.jpg")
Tagging.create(business_id: 32, tag_id: 4)
Review.create(business_id: 32, user_id: 4, rating: 4, content: "Definitely one of the nicest malls out there")
Review.create(business_id: 32, user_id: 2, rating: 5, content: "Been going here for years. Stores always change but the vibes are always amazing.")
Review.create(business_id: 32, user_id: 11, rating: 4, content: "Nice and relaxing atmosphere while you shop!")
Review.create(business_id: 32, user_id: 6, rating: 4, content: "It's a really nice mall, not much else to say!")
Image.create(business_id: 32, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473444003/wfvf1_ee9tz4.jpg")
Image.create(business_id: 32, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473444003/wfvf2_s30cce.jpg")
Image.create(business_id: 32, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473444003/wfvf3_ahe9uy.jpg")

Business.create(name: "Santana Row", lat: 37.320311, lng: -121.947942, street_address: "377 Santana Row", city_state_address: "San Jose, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473444467/santana_wopejs.jpg")
Tagging.create(business_id: 33, tag_id: 4)
Review.create(business_id: 33, user_id: 3, rating: 4, content: "If Valley Fair seemed subpar, this will blow your socks off")
Review.create(business_id: 33, user_id: 8, rating: 4, content: "Such a high end area, you can even see some super nice cars in the area every time you come by!")
Review.create(business_id: 33, user_id: 5, rating: 4, content: "Tons of activities in the area like car shows and whatnot.")
Image.create(business_id: 33, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473444467/santana1_b74wqy.jpg")
Image.create(business_id: 33, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473444467/santana2_ffw4oy.jpg")
Image.create(business_id: 33, image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/c_scale,h_200/v1473444467/santana3_nvlkvv.jpg")

# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )



#Arts & Entertainment
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
#
# Business.create(name: "", lat: , lng:, street_address: "", city_state_address: "", profile_image_url: "")
# Tagging.create(business_id: , tag_id: )
# Review.create(business_id: , user_id: , rating: , content: "")
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )
# Image.create(business_id: , image_url: )

####### DEVELOPMENT TEST DATA
#
# Business.create(name: "Whole Foods Market SoMa", lat: 37.781150, lng: -122.399778, street_address: "399 4th St", city_state_address: "San Francisco, CA", profile_image_url:"http://res.cloudinary.com/dnmknegr2/image/upload/v1473178655/90s_jmkn6b.jpg")
# Tagging.create(business_id: 2, tag_id: 1)
# Tagging.create(business_id: 2, tag_id: 4)
# Review.create(business_id: 2, user_id: 3, rating: 4, content: "vegetables are hella fresh")
# Review.create(business_id: 2, user_id: 2, rating: 3, content: "cashier could've been nice imo")
#
#
# Business.create(name: "Century San Francisco Centre 9", lat: 37.783826, lng: -122.405800, street_address: "845 Market St, 5th Fl", city_state_address: "San Francisco, CA", profile_image_url:"http://res.cloudinary.com/dnmknegr2/image/upload/v1473178655/ls_vmfxgl.jpg")
# Tagging.create(business_id: 3, tag_id: 2)
# Tagging.create(business_id: 3, tag_id: 5)
# Review.create(business_id: 3, user_id: 4, rating: 4, content: "cozy seats are the bestttt")
# Review.create(business_id: 3, user_id: 1, rating: 3, content: "$7 for soda LOL")
#
#
# # ACTUAL BUSINESSES
# Business.create(name: "Gelateria Naia", lat: 37.799810, lng: -122.409228, street_address: "520 Columbus Ave", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473141688/gelateria_naia_eyjx3r.jpg")
# Tagging.create(business_id: 4, tag_id: 1)
# Review.create(business_id: 4, user_id: 4, rating: 4, content: "wow it's so good")
# Review.create(business_id: 4, user_id: 1, rating: 3, content: "makes me want to move to Italy!!")
#
# Business.create(name: "Holy Gelato!", lat: 37.762327, lng: -122.465989, street_address: "1392 9th Ave", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473141688/holy_gelato_nq5rty.jpg")
# Tagging.create(business_id: 5, tag_id: 1)
# Review.create(business_id: 5, user_id: 2, rating: 5, content: "literally better than chocolate")
# Review.create(business_id: 5, user_id: 3, rating: 4, content: "the pistachio will get you hooked")
#
# Business.create(name: "La Copa Loca!", lat: 37.755594, lng: -122.417848, street_address: "3150 22nd St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473141688/lacopapoca_xcje5g.jpg")
# Tagging.create(business_id: 6, tag_id: 1)
# Review.create(business_id: 6, user_id: 1, rating: 5, content: "i sold my house for this")
# Review.create(business_id: 6, user_id: 2, rating: 4, content: "i should've tried gelato sooner!!!")
#
# Business.create(name: "Lush Gelato", lat: 37.800671, lng: -122.408856, street_address: "576 Union St", city_state_address: "San Francisco, CA", profile_image_url: "http://res.cloudinary.com/dnmknegr2/image/upload/v1473141688/lush_gelato_rmsknu.jpg")
# Tagging.create(business_id: 7, tag_id: 1)
# Review.create(business_id: 7, user_id: 3, rating: 4, content: "better than ice cream for sure")
# Review.create(business_id: 7, user_id: 1, rating: 3, content: "my gelato kind of melted")
